### ISSUE TITLE
needed xstate-c++

### ISSUE THREAD

**Issue by edbek** [davidkpiano/xstate-python#13]
needed xstate-c++

**Comment by davidkpiano** [comment]
Feel free to make it! An SCXML interpreter for C++ already exists: https://github.com/jp-embedded/scxmlcc

**Comment by edbek** [comment]
it is a compiler, not a SCXML interpreter. In addition, it is built on a boost that I would like to get away from.

**Comment by davidkpiano** [comment]
Ah, my mistake. Anyway, I don't know too much C++, and the algorithms are here: https://www.w3.org/TR/scxml/

Let me know if you need any help making it. I believe in you!
