### ISSUE TITLE
Compatibility with older python versions

### ISSUE THREAD

**Issue by Aluriak** [davidkpiano/xstate-python#23]
Hi !

The use of `from __future__ import annotations`, and subsequent postponed annotations, prevents xstate to be used with version 3.6 of python, despite being [still officially supported](https://www.python.org/downloads).

Can you ensure the compatibility with that version ?

**Comment by JovaniPink** [comment]
Hi Aluriak,

You are correct 3.6 is still supported and that using postponed annotations is 3.7+ [pep-0563](https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7).

I'll work on a solution. Cheers.
