### ISSUE TITLE
Class-level definitions of instances members

### ISSUE THREAD

**Issue by Aluriak** [davidkpiano/xstate-python#24]
In most of xstate's classes, we find class attributes mirroring the instances attributes. For instance, in `event.py` : 

    class Event:
        name: str  # <- class attribute
        data: Dict  # <- class attribute

        def __init__(self, name: str, data: Optional[Dict] = None):
            self.name = name
            self.data = data

What is the point of the two class attribute definition ? Are they used elsewhere ?

**Comment by davidkpiano** [comment]
They're used for type-checking.

**Comment by Aluriak** [comment]
Ok, good to know. Thanks !
