### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by mr-bjerre** [davidkpiano/xstate-python#30]
In `setup.cfg` the following dependencies are listed

```
ipython>=6
nbformat>=4
nbconvert>=5
requests>=2
```

Isn't that a mistake?

I also see `Js2Py` being used in `scxml.py` but only listed in `requirements_dev.txt`. That seems wrong as well.

Let me know if any of this is intended and then I'll fix in a PR.

**Comment by davidkpiano** [comment]
The `setup.cfg` dependencies look wrong to me, too. And yes, `Js2Py` should be included.
