### ISSUE TITLE
Improve development workflow

### ISSUE THREAD

**Issue by mr-bjerre** [davidkpiano/xstate-python#33]
I'm considering making a PR that improves the workflow like 

1. adding static type-checker like [mypy](http://mypy-lang.org/) - you can freely mix static and dynamic typing
1. a linter [flake8](https://pypi.org/project/flake8/)
1. formatters like [black](https://github.com/psf/black) and [isort](https://pycqa.github.io/isort/)
1. add GitHub Actions, e.g. [CodeCoverage](https://github.com/marketplace/codecov)
1. improve dependency management with [poetry](https://python-poetry.org/) - might want to skip this since there aren't really any dependencies. 
1. add docs using something like [sphinx](https://www.sphinx-doc.org/en/master/) - or some alternative?

Let me know what you think of the different suggestions - with VS Code Remote Containers in place it is easy to streamline the development environment.

**Comment by davidkpiano** [comment]
Those suggestions sound great; I'm not strongly opinionated on any; just opinionated on the _existence_ of them (they should exist in the project) 👍
